# Step 1: Use an official Python runtime as a base image
FROM python:3.10

# Step 2: Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Step 3: Set the working directory
WORKDIR /project

# Step 4: Copy the Python dependencies file into the container
COPY requirements.txt /project/

# Install system dependencies, including tzdata
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    libssl-dev \
    netcat-openbsd \
    libpq-dev \
    tzdata \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y gcc


RUN pip install --upgrade pip setuptools wheel



# Step 5: Install Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Step 6: Copy the entire Django project into the container
COPY . /project/

# Step 7: Expose the Django development server port
EXPOSE 8000

# Step 8: Ensure the startup script is executable
RUN chmod +x /project/startup.sh

# Step 9: Run the startup script
CMD ["./startup.sh"]
