# Generated by Django 4.2.14 on 2024-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_category_product_contactus_note_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Coupon Used Count'),
        ),
    ]
