# Generated by Django 4.2.14 on 2024-08-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_productattribute_productattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='admin_panel.product'),
            preserve_default=False,
        ),
    ]
