# Generated by Django 4.2.14 on 2024-08-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0007_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banner_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banner_updated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplate_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplate_updated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
