# Generated by Django 4.2.14 on 2024-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_cms_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='cc',
        ),
    ]
