# Generated by Django 4.2.14 on 2024-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_rename_body_emailtemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], max_length=20, verbose_name='Address type'),
        ),
    ]
