# Generated by Django 4.2.14 on 2024-08-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
