# Generated by Django 4.2.14 on 2024-10-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_emaillogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
