# Generated by Django 4.2.14 on 2024-10-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_alter_banner_options_banner_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-updated_at', 'id']},
        ),
    ]
