# Generated by Django 4.2.14 on 2024-10-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_orderstatuslogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatusLogs',
        ),
    ]
