# Generated by Django 4.2.14 on 2024-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_alter_usereventtracking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventtracking',
            name='object_info',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereventtracking',
            name='requested_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
