# Generated by Django 4.2.14 on 2024-08-20 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0010_rename_body_emailtemplate_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment gateway.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment gateway was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the payment gateway was last modified.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the payment gateway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_gateway', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the payment gateway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_gateway', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.FloatField(null=True, verbose_name='Grand Total')),
                ('shipping_method', models.CharField(choices=[('STD', 'Standard Shipping'), ('EXP', 'Express Shipping'), ('OVN', 'Overnight Shipping'), ('PUP', 'In-Store Pickup')], default='STD', max_length=3, verbose_name='Shipping Method')),
                ('shipping_charges', models.FloatField(null=True, verbose_name='Shipping Charges')),
                ('AWB_NO', models.CharField(blank=True, max_length=100, null=True, verbose_name='AWB Number')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('O', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered')], max_length=1, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the payment gateway was last modified.')),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='admin_panel.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='admin_panel.coupon', verbose_name='Coupon')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the payment gateway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_create', to=settings.AUTH_USER_MODEL)),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='order_management.paymentgateway', verbose_name='Payment Gateway')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='admin_panel.address')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the payment gateway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_update', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
