# Generated by Django 4.2.14 on 2024-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered')], default=1, max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
