# Generated by Django 4.2.14 on 2024-08-22 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_address_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_management', '0005_alter_userorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_gateway', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_gateway', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='admin_panel.address', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='admin_panel.address', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
