# Generated by Django 4.2.14 on 2024-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_userwishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
