# Generated by Django 4.2.14 on 2024-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_alter_userorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_ord_id', models.CharField(max_length=50, verbose_name='Payment Order Id')),
                ('pay_status', models.CharField(max_length=50, verbose_name='Payment Status')),
                ('response_dict', models.TextField(verbose_name='Response In Str Form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Order Id'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='status',
            field=models.CharField(choices=[('S', 'Successful'), ('P', 'Pending'), ('W', 'Waiting')], default='W', max_length=1, verbose_name='Status'),
        ),
    ]
