# Generated by Django 4.2.14 on 2024-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_paymentlogs_paymentgateway_payment_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='payment_order_id',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='status',
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful'), ('F', 'Failed'), ('C', 'Cancelled')], default='P', max_length=1, verbose_name='Payment Status'),
        ),
    ]
